name: Build Node.js APK (x86_64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout workflow repo
      uses: actions/checkout@v4

    - name: Clone OpenWrt master
      run: |
        git clone --depth 1 https://github.com/openwrt/openwrt.git

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib gperf unzip \
          libncurses5-dev zlib1g-dev libssl-dev python3 python3-apt python3-distutils-extra rsync subversion git wget file

    - name: Update and install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        # 删除默认packages中的node包
        rm -rf package/feeds/packages/node*
        ./scripts/feeds install -a -p node

    - name: Debug package path
      working-directory: ./openwrt
      run: |
        echo "Listing package directory..."
        ls -l package
        echo "Listing feeds directory..."
        ls -l package/feeds
        echo "Listing node feed directory..."
        ls -l package/feeds/node
        echo "Listing node packages (if exist)..."
        ls -l package/feeds/node/node || echo "No node directory"

    - name: Configure x86_64 build
      working-directory: ./openwrt
      run: |
        make defconfig
        echo "CONFIG_TARGET_x86=y" >> .config
        echo "CONFIG_TARGET_x86_64=y" >> .config
        echo "CONFIG_TARGET_x86_64_Generic=y" >> .config
        echo "CONFIG_PACKAGE_node=y" >> .config
        echo "CONFIG_NODEJS_20=y" >> .config
        echo "# CONFIG_NODEJS_22 is not set" >> .config
        echo "# CONFIG_NODEJS_24 is not set" >> .config
        make defconfig

    - name: Compile Node.js for x86_64
      working-directory: ./openwrt
      run: |
        # 这里改成你 Debug 发现的正确路径，比如 package/node/compile
        make package/node/compile V=s -j$(nproc)

    - name: Upload Node.js APK
      uses: actions/upload-artifact@v4
      with:
        name: node-apk-x86_64
        path: openwrt/bin/packages/*/node_*.apk
