name: Build Node.js APK (x86_64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout workflow repo
      uses: actions/checkout@v4

    - name: Clone OpenWrt master
      run: |
        git clone --depth 1 https://github.com/openwrt/openwrt.git

    - name: Install build dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib gperf unzip \
          libncurses5-dev zlib1g-dev libssl-dev python3 python3-apt python3-distutils-extra rsync subversion git wget file

    - name: Update and install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        # 删除默认 packages 中的 node 包，避免冲突
        rm -rf package/feeds/packages/node*
        ./scripts/feeds install -a -p node

    - name: Debug package paths
      working-directory: ./openwrt
      run: |
        echo "Listing package directory..."
        ls -l package || echo "package directory not found"

        echo "Listing package/feeds directory..."
        ls -l package/feeds || echo "package/feeds directory not found"

        echo "Listing package/feeds/node directory..."
        ls -l package/feeds/node || echo "package/feeds/node directory not found"

        echo "Checking for node package directory under package/feeds/node..."
        if [ -d package/feeds/node/node ]; then
          ls -l package/feeds/node/node
        else
          echo "No node directory under package/feeds/node"
        fi

    - name: Configure x86_64 build
      working-directory: ./openwrt
      run: |
        make defconfig
        echo "CONFIG_TARGET_x86=y" >> .config
        echo "CONFIG_TARGET_x86_64=y" >> .config
        echo "CONFIG_TARGET_x86_64_Generic=y" >> .config
        echo "CONFIG_PACKAGE_node=y" >> .config
        echo "CONFIG_NODEJS_20=y" >> .config
        echo "# CONFIG_NODEJS_22 is not set" >> .config
        echo "# CONFIG_NODEJS_24 is not set" >> .config
        make defconfig

    - name: Compile Node.js for x86_64
      working-directory: ./openwrt
      run: |
        # 根据 Debug package paths 的结果替换下面路径
        # 例如：make package/node/compile 或 make package/feeds/node/<实际包名>/compile
        make package/node/compile V=s -j$(nproc)

    - name: Upload Node.js APK
      uses: actions/upload-artifact@v4
      with:
        name: node-apk-x86_64
        path: openwrt/bin/packages/*/node_*.apk
